
stm_bm(["menu4fd9",730,"","icon/blank.gif",0,"","",0,3,0,0,1000,1,0,0,"","100%",0,0,1,1,"default","hand",""],this);
stm_bp("p0",[0,4,0,0,0,0,0,0,100,"",-2,"",-2,90,0,0,MenuTextColor,"","",3,0,0,MenuTextColor]);
stm_ai("p0i0",[0,"<?=__('Каталог');?>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0,0,1,1,MenuColor,0,MenuColorActive,0,"","",3,3,1,1,MenuColor,MenuColorActiveBorder,MenuTextColor,MenuTextColor,"8pt 'Tahoma','Arial'","8pt 'Tahoma','Arial'",0,0],60,20);
stm_bp("p1",[1,4,0,0,2,3,16,0,100,"",-2,"",-2,100,2,3,MenuTextColor,MenuColor,"",3,1,1,""]);
stm_aix("p1i0","p0i0",[0,"<?=__('Просмотр содержимого');?>","","",-1,-1,0,"?p=catalog","_self","","","icon/folder_images.gif","icon/folder_images.gif",16,16,0,"","",0,0,0,0]);
stm_aix("p1i1","p1i0",[0,"<?=__('Создать...');?>","","",-1,-1,0,"","_self","","","img/arrow_r.gif","",7,7]);
stm_bp("p2",[1,2,-1,0,3,3,18,0,100,"",-2,"",-2,100,2,2,MenuTextColor,MenuColor,"",3,1,1,""]);
stm_aix("p2i0","p1i0",[0,"<?=__('Новый каталог');?>","","",-1,-1,0,"javascript:miniWin('catalog/adm_catalog_new.php','650','630')","_self","","","icon/folder_add.gif","icon/folder_add.gif",16,16]);
stm_aix("p2i1","p2i0",[0,"<?=__('Новая страница');?>","","",-1,-1,0,"javascript:miniWin('page/adm_pages_new.php','650','630')","_self","","","icon/page_new.gif","icon/page_new.gif",16,16]);
stm_ep();
stm_ep();
stm_aix("p0i1","p0i0",[1,"<?=__('Администраторы');?>&nbsp;&nbsp;","","",-1,-1,0,"","_self","","","","",5,20]);
stm_bpx("p3","p2",[1,4,-1,0,3,3,16]);
stm_aix("p3i0","p1i0",[0,"<?=__('Обзор администраторов');?>","","",-1,-1,0,"?p=users","_self","","","icon/group.gif","icon/group.gif",16,16]);
stm_aix("p3i1","p3i0",[0,"<?=__('Создать администратора');?>","","",-1,-1,0,"javascript:miniWin('users/adm_users_new.php',500,400)","_self","","","icon/group_add.gif","icon/group_add.gif",16,16]);
stm_ep();
stm_aix("p0i2","p0i1",[1,"<?=__('Настройка');?>&nbsp;&nbsp;"]);
stm_bpx("p4","p3",[]);
stm_aix("p4i1","p2i0",[0,"<?=__('Система');?>","","",-1,-1,0,"javascript:miniWin('system/adm_system.php',510,480);","_self","","","icon/joystick.gif","icon/joystick.gif"]);
stm_aix("p4i2","p2i0",[0,"<?=__('Keywords & Titles');?>","","",-1,-1,0,"javascript:miniWin('system/adm_system_promo.php',500,600);","_self","","","icon/xhtml.gif","icon/xhtml.gif"]);
stm_aix("p4i3","p2i0",[0,"<?=__('Фотогалерея');?>","","",-1,-1,0,"javascript:miniWin('system/adm_system_watermark.php',600,600)","_self","","","icon/photo_album.gif","icon/photo_album.gif"]);
stm_ep();
stm_aix("p0i3","p0i1",[1,"<?=__('Сервис');?>&nbsp;&nbsp;"]);
stm_bpx("p7","p2",[1,4,-1,0,3,3,7]);
stm_aix("p7i0","p1i1",[0,"<?=__('Обзор...');?>"]);
stm_bpx("p8","p2",[]);
stm_aix("p8i1","p1i0",[0,"<?=__('Обзор новостей');?>","","",-1,-1,0,"?p=news","_self","","","icon/page_lightning.gif","icon/page_lightning.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор баннеров');?>","","",-1,-1,0,"?p=banner","_self","","","icon/page_refresh.gif","icon/page_refresh.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор текстовых блоков');?>","","",-1,-1,0,"?p=menu","_self","","","icon/page_attach.gif","icon/page_attach.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор отзывов');?>","","",-1,-1,0,"?p=gbook","_self","","","icon/page_error.gif","icon/page_error.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('База рассылки');?>","","",-1,-1,0,"?p=news_writer","_self","","","icon/comments.gif","icon/comments.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор ссылок');?>","","",-1,-1,0,"?p=links","_self","","","icon/page_link.gif","icon/page_link.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор опросов');?>","","",-1,-1,0,"?p=opros","_self","","","icon/page_edit.gif","icon/page_edit.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор фотогалереи');?>","","",-1,-1,0,"?p=photo","_self","","","icon/photo_album.gif","icon/photo_album.gif"]);
stm_aix("p8i2","p2i0",[0,"<?=__('Обзор RSS каналов');?>","","",-1,-1,0,"?p=rssgraber","_self","","","icon/rss.gif","icon/rss.gif"]);
stm_ep();
stm_aix("p7i1","p1i1",[]);
stm_bpx("p9","p2",[]);
stm_aix("p9i0","p2i1",[0,"<?=__('Новая страница');?>","","",-1,-1,0,"javascript:miniWin('page/adm_pages_new.php','630','600')"]);
stm_aix("p9i1","p2i1",[0,"<?=__('Новый баннер');?>","","",-1,-1,0,"javascript:miniWin('banner/adm_baner_new.php','630','530')"]);
stm_aix("p9i2","p2i1",[0,"<?=__('Новый текстовый блок');?>","","",-1,-1,0,"javascript:miniWin('menu/adm_menu_new.php','630','530')"]);
stm_aix("p9i3","p2i1",[0,"<?=__('Новая новость');?>","","",-1,-1,0,"javascript:miniWin('news/adm_news_new.php?id=3',630,550)"]);
stm_aix("p9i4","p2i1",[0,"<?=__('Новый отзыв');?>","","",-1,-1,0,"javascript:miniWin('gbook/adm_gbook_new.php?id=3',630,530)"]);
stm_aix("p9i5","p2i1",[0,"<?=__('Новая рассылка');?>","","",-1,-1,0,"javascript:miniWin('news_writer/adm_news_writer_new.php?id=2',400,300)"]);
stm_aix("p9i6","p2i1",[0,"<?=__('Новая ссылка');?>","","",-1,-1,0,"javascript:miniWin('links/adm_links_new.php',630,550)"]);
stm_aix("p9i6","p2i1",[0,"<?=__('Новый опрос');?>","","",-1,-1,0,"javascript:miniWin('opros/adm_opros_new.php',630,530)"]);
stm_aix("p9i6","p2i1",[0,"<?=__('Новый RSS канал');?>","","",-1,-1,0,"javascript:miniWin('rssgraber/adm_chanels_new.php',400,480)"]);
stm_ep();
stm_ep();

stm_aix("p0i6","p0i1",[1,"<?=__('База');?>&nbsp;&nbsp;&nbsp;"]);
stm_bpx("p10","p3",[]);
stm_aix("p10i1","p2i0",[0,"<?=__('SQL запрос');?>","","",-1,-1,0,"javascript:miniWin('sql/adm_sql.php',500,430)","_self","","","icon/database_key.gif","icon/database_key.gif"]);
stm_aix("p10i2","p2i0",[0,"<?=__('SQL загрузка файла');?>","","",-1,-1,0,"javascript:miniWin('sql/adm_sql_file.php',500,430)","_self","","","icon/database_connect.gif","icon/database_connect.gif"]);
stm_aix("p10i3","p2i0",[0,"<?=__('Создание резервной копии');?>","","",-1,-1,0,"javascript:miniWin('dumper/dumper.php',500,430)","_self","","","icon/database_save.gif","icon/database_save.gif"]);
stm_ep();